### ISSUE TITLE
Cannot download semantic annotations

### ISSUE THREAD

**Issue by arjung128** [facebookresearch/habitat-challenge#114]
Hi, I've been having trouble downloading the semantic annotations. I am using:

`python -m habitat_sim.utils.datasets_download --username [username] --password [password] --uids hm3d_val --data-path data`

I also just re-installed the `challenge-2022` versions of both habitat-sim and habitat-lab as instructed (v0.2.1 for both). This gives me the following error:

 ```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    82  100    82    0     0     10      0  0:00:08  0:00:08 --:--:--    18
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
100 10533  100 10533    0     0    981      0  0:00:10  0:00:10 --:--:--     0
Traceback (most recent call last):
  File "/anaconda3/envs/habitat/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/habitat/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim/utils/datasets_download.py", line 688, in <module>
    main(sys.argv[1:])
  File "/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim/utils/datasets_download.py", line 683, in main
    uid, data_path, args.username, args.password, replace
  File "/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim/utils/datasets_download.py", line 520, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/anaconda3/envs/habitat/lib/python3.7/tarfile.py", line 1580, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

It seems to go away when I install habitat-sim with `conda install habitat-sim withbullet headless -c conda-forge -c aihabitat`. But with this workaround, the semantic annotations don't seem to get downloaded: `habitat-challenge/data/scene_datasets/hm3d/val/00800-TEEsavR23oF` and `habitat-challenge/data/versioned_data/hm3d-1.0/hm3d/val/00800-TEEsavR23oF` do not contain the semantic annotations (they only contain `TEEsavR23oF.basis.glb` and `TEEsavR23oF.basis.navmesh`). 

Additionally, I am unable to use `--uids hm3d_semantics` or `--uids hm3d_semantics_minival`, which results in the following error: `Data download failed, no datasource named hm3d_semantics`.

Any ideas what I might be doing wrong? Thanks!

**Comment by ykarmesh** [comment]
We recently sent out this msg to all the participants:

Due to unforeseen circumstances surrounding the availability of the HM3D-Semantic v0.1 dataset we have decided to extend the challenge deadline, tentatively by three months. We realize many participants are impacted by this and apologize for the disruption. We will follow up with a more exact updated challenge timeline soon. In the meantime, the Test Standard phase leaderboard continues to be open and you are welcome to report results from it in your papers. To not disadvantage anyone who has already submitted, we will reset the Test Challenge leaderboard submission count. We plan to provide an update about the challenge at the CVPR 2022 Embodied AI workshop, and to announce challenge results at the upcoming NeurIPS 2022 conference.

Apologies for the inconvenience.

**Comment by ykarmesh** [comment]
@arjung128 The HM3D-Semantic data is available for download again.
