### ISSUE TITLE
Challenge resolution

### ISSUE THREAD

**Issue by edbeeching** [facebookresearch/habitat-challenge#20]
Hello, thank you for creating this years challenge!

Regarding the resolution, for object-nav the config file has a resolution of WIDTH: 640, HEIGHT: 480. Will it be possible to use lower resolutions for the challenge? I believe this was available last year but wish to confirm.

Thank you.

**Comment by dhruvbatra** [comment]
You're welcome! We're happy to hear of your (continued) interest. 

Participants are free to use lower resolutions for their models/methods. We are simply specifying what resolution is available at test time.

**Comment by edbeeching** [comment]
Thank you for such a prompt response. My concern is if I, for example, train with the simulator running at 128x96 and then test at 640x480 and manually resize with OpenCV, the anti-aliasing/downsampling may not achieve the same result. Perhaps my concern is unfounded and the model will be robust to this change. Time will tell. 

I think last year other config files were available at test time? or perhaps I am getting mixed up with another competition.

**Comment by dhruvbatra** [comment]
No, that's a reasonable question. 

> train with the simulator running at 128x96 and then test at 640x480 and manually resize with OpenCV, the anti-aliasing/downsampling may not achieve the same result.

Yes, that could lead to differences. I would expect them to be minor. I assume you don't want to train with 640x480 --> downsized to 128x96 because that would be slower to train? 

> I think last year other config files were available at test time? 

I don't think so, but perhaps @mathfac or @abhiskk can confirm.

**Comment by mathfac** [comment]
@edbeeching, previous year challenge was run with a fixed resolution 256x256, you [can check it here](https://github.com/facebookresearch/habitat-challenge/blob/8619f8fba092c106937d7f30dd551362bb76c162/habitat-challenge-data/challenge_pointnav.local.rgbd.yaml#L9).

Training with 640x480 instead of 128x96 shouldn't hit performance significantly, as a render call will be needed anyway. 
I would advice next options:
1. Train with 640x480 and downsample to 128x96 during training to have same frame transformation.
Or
2. Train with 128x96, and run evaluation on val split with 640x480 and downsampling and check that success metrics doesn't change much.

**Comment by edbeeching** [comment]
@mathfac 
Thank you for confirmation, I must of been thinking of another competition.
I was expecting the rendering to be slower with the higher resolutions, as per the table on the habitat-sim github page, https://github.com/facebookresearch/habitat-sim#performance.

Thank you for the advice, I will compare the two options and see what works best.
