### ISSUE TITLE
Potential issue with shortest path or success criteria in ObjectNav

### ISSUE THREAD

**Issue by devendrachaplot** [facebookresearch/habitat-challenge#32]
Hi,
I was evaluating the shortest path for the ObjectNav task. The second and third episode on val_mini seem to fail with the shortest path. 

Looking at the path, it seems like the path is correct. The agent is navigating towards an instance of the target category, maybe there's some issue with success criteria?

**Comment by mathfac** [comment]
@devendrachaplot looking into this. If that the case, most probably issue is with shortest path, not metrics itself.

**Comment by mathfac** [comment]
@devendrachaplot, checked the episodes. For portion of the episodes shortest path will not lead to success. Success distance is 0.1m to a view point of the target object, but shortest path sometimes stops up to 0.2m.
I would advice use [new Shortestpath Planner](https://github.com/facebookresearch/habitat-api/pull/375) instead of precalculated shortest paths:
```
goal_radius = config.TASK.SUCCESS.SUCCESS_DISTANCE / 2
follower = ShortestPathFollower(env.habitat_env.sim, goal_radius, False)
env.reset()
        while not env.habitat_env.episode_over:
            best_action = follower.get_next_action(
                closest_view_point.agent_state.position,
            )
            observations, reward, done, info = env.step(best_action)
```

With original shortest path (No success, distance_to_goal: 0.17m): 
<img width="1429" alt="Screenshot 2020-05-01 13 29 14" src="https://user-images.githubusercontent.com/877440/80839530-4d8fdc00-8bb0-11ea-9110-0adaa1e977ee.png">
With new Shortestpath Planner: (Success, distance_to_goal: 0.04m): 
<img width="1385" alt="Screenshot 2020-05-01 13 29 05" src="https://user-images.githubusercontent.com/877440/80839805-ce4ed800-8bb0-11ea-9ad0-8e09c2562c74.png">

**Comment by devendrachaplot** [comment]
Great, thanks a lot!

I had one quick follow-up question:
"Success distance is 0.1m to a view point of the target object" -> How are these view points obtained?
